"""bills: add Bill and BillMember models

Revision ID: bd2a43b28358
Revises: db31e1c017a1
Create Date: 2025-05-11 17:25:51.758827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd2a43b28358'
down_revision = 'db31e1c017a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_transaction')
    # ### end Alembic commands ###
