"""changed applied transfer logic

Revision ID: c7dd71fbc444
Revises: bd2a43b28358
Create Date: 2025-05-12 20:36:55.986331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7dd71fbc444'
down_revision = 'bd2a43b28358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.drop_column('settled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settled', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
